Greenpack
itzTheMeow/NinjaIOUtils pull request #92
Opened 2024-02-18 17:53 UTC by kochamale123

added green weapons nd stuff

2024-02-20 04:53 UTC, itzTheMeow requested changes
description change, everything else looks good

2024-02-20 04:53 UTC, itzTheMeow commented on texturepacks/greenpack/_meta.json
make the description a little more descriptive

2024-02-20 16:25 UTC, kochamale123 commented on texturepacks/greenpack/_meta.json
so i should do it all over again just changing the description right

2024-02-20 18:57 UTC, kochamale123 commented on texturepacks/greenpack/_meta.json
done

2024-02-21 00:51 UTC, itzTheMeow approved these changes
cool

2024-02-21 00:51 UTC, merged